http:
  port: ${PORT}
https:
  port: ${PORT}
apiEndpoints:
  express:
    host: "*"
    paths: '/expressApi/v1/*'
serviceEndpoints:
  expressService:
    url: 'https://express-server-production-bafc.up.railway.app'
policies:
  - proxy
  - log
pipelines:
  expressPipeline:
    apiEndpoints:
      - express
    policies:
      - log:
        - action:
            message: "LOG ${req.method} ${req.originalUrl} ${req.url} ${req.ip} ${req.protocol} ${res.statusCode}"
      - proxy:
          - action:
              serviceEndpoint: expressService 

