http:
  port: ${PORT}
apiEndpoints:
  express:
    host: 0.0.0.0
    paths: '/expressApi/v1/*'
serviceEndpoints:
  expressService:
    url: 'http://express-server.railway.internal:7083'
policies:
  - proxy
pipelines:
  expressPipeline:
    apiEndpoints:
      - express
    policies:
      - proxy:
          - action:
              serviceEndpoint: expressService 

