http:
  port: ${PORT}
apiEndpoints:
  express:
    host: "*"
    paths: '/expressApi/v1/*'
  flask:
    host: "*"
    paths: '/flaskAPI/v1/*'
  reporting:
    host: "*"
    paths: '/reporting-service/v1/*'
serviceEndpoints:
  expressService:
    url: 'https://express-server-production-bafc.up.railway.app'
  flaskService:
    url: 'https://property-service-production.up.railway.app'
  reportingService:
    url: 'https://reporting-service-production.up.railway.app'
policies:
  - proxy
  - log
pipelines:
  expressPipeline:
    apiEndpoints:
      - express
    policies:
      - log:
        - action:
            message: "LOG ${req.method} ${req.originalUrl} ${req.url} ${req.ip} ${res.statusCode}"
      - proxy:
          - action:
              serviceEndpoint: expressService 
  flaskPipeline:
    apiEndpoints:
      - flask
    policies:
      - log:
        - action:
            message: "LOG ${req.method} ${req.originalUrl} ${req.url} ${req.ip} ${req.protocol} ${res.statusCode}"
      - proxy:
          - action:
              serviceEndpoint: flaskService 
  reportingPipeline:
    apiEndpoints:
      - reporting
    policies:
      - log:
        - action:
            message: "LOG ${req.method} ${req.originalUrl} ${req.url} ${req.ip} ${req.protocol} ${res.statusCode}"
      - proxy:
          - action:
              serviceEndpoint: reportingService 

